version: "3.9"
services:
  blender:
    build:
      context: ./bpy
      target: dev
    volumes:
    - ./:/usr/src/app
    - ./bpy/.venv:/usr/src/app/.venv # workaround
    command: /bin/sh -c "while sleep 1000; do :; done"
