name: github pages

on:
  push:
    branches:
      - main

jobs:
  blender:
    runs-on: ubuntu-20.04
    container: cactice/sverchok:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache
        id: cache-glb
        uses: actions/cache@v2
        with:
          path: ./next/public/glb/**
          key: ${{ hashFiles('./next/public/glb/**')  }}-glb
      -
        name: Generate glb
        if: steps.cache-glb.outputs.cache-hit != 'true'
        working-directory: ./bpy
        run: |
          blender -P install_sverchok.py -b
          blender -P json_to_glb.py -b --input_dir=../sverchok/ empty.blend
      -
        name: Upload glb
        if: steps.cache-glb.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: glb-dir
          path: ./next/public/glb/
  deploy:
    needs: [blender]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./next
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Download glb files
        uses: actions/download-artifact@v2
        with:
          name: glb-dir
          path: ./next/public/glb
      - name: Yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./next/out
